# Generated by Django 4.2.1 on 2023-05-18 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha',
            field=models.DateField(db_column='Fecha', default=datetime.date(2023, 5, 18)),
        ),
    ]
