# Generated by Django 4.2.1 on 2023-05-18 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_evaluacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha',
            field=models.DateField(db_column='Fecha', default=datetime.datetime(2023, 5, 18, 14, 37, 55, 268226, tzinfo=datetime.timezone.utc)),
        ),
    ]
