# Generated by Django 4.2.1 on 2023-07-16 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_eval_proced'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='cod_cl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='API.cliente'),
        ),
    ]
