# Generated by Django 4.1.3 on 2023-07-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_evaluacion_cod_cl'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta_evaluacion',
            name='respuesta',
            field=models.TextField(null=True),
        ),
    ]
